name: my_new_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  shared_preferences: ^2.2.3
  
  # حزمة السوكيت المستقرة الخاصة بك
  socket_io_client: ^3.1.6
  cupertino_icons: ^1.0.8
  
  # 🌟 التعديل الحاسم: خفض الإصدار إلى 14.7.10 لحل تعارض حزمة الـ web الداعمة للسوكيت والفايربيس معاً
  firebase_core: 2.32.0
  firebase_messaging: 14.7.10
  
  # النسخ القديمة المستقرة المتوافقة مع كود الإشعارات والصوت الخاص بك
  audioplayers: 5.2.1
  flutter_local_notifications: 16.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4
  flutterfire_cli: ^1.4.0

# إعدادات الأيقونة
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/notification_sound_for_whatsapp.mp3
