// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE2oqO9VQmcQVH-E-EDTVxuYHUNVe5ygE',
    appId: '1:695616450101:web:02fc9b32b60dbd090e4b7c',
    messagingSenderId: '695616450101',
    projectId: 'clickpharma-88208',
    authDomain: 'clickpharma-88208.firebaseapp.com',
    storageBucket: 'clickpharma-88208.firebasestorage.app',
    measurementId: 'G-355HV9GNPX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-WYrbN7OquZUUpbfRRScEfB_LAzgGsTo',
    appId: '1:695616450101:android:1cd87fc550bfb7b40e4b7c',
    messagingSenderId: '695616450101',
    projectId: 'clickpharma-88208',
    storageBucket: 'clickpharma-88208.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2snmyjmKot5Oxn4A8_EVFjAzokJFDJl4',
    appId: '1:695616450101:ios:8fb8b727f064d4ae0e4b7c',
    messagingSenderId: '695616450101',
    projectId: 'clickpharma-88208',
    storageBucket: 'clickpharma-88208.firebasestorage.app',
    iosBundleId: 'com.example.myNewApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2snmyjmKot5Oxn4A8_EVFjAzokJFDJl4',
    appId: '1:695616450101:ios:8fb8b727f064d4ae0e4b7c',
    messagingSenderId: '695616450101',
    projectId: 'clickpharma-88208',
    storageBucket: 'clickpharma-88208.firebasestorage.app',
    iosBundleId: 'com.example.myNewApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDE2oqO9VQmcQVH-E-EDTVxuYHUNVe5ygE',
    appId: '1:695616450101:web:c4cb35448ed084fa0e4b7c',
    messagingSenderId: '695616450101',
    projectId: 'clickpharma-88208',
    authDomain: 'clickpharma-88208.firebaseapp.com',
    storageBucket: 'clickpharma-88208.firebasestorage.app',
    measurementId: 'G-Z3HPQWKBK9',
  );
}
