# جلب مسار Flutter الافتراضي سحابياً
flutter_root = ENV['FLUTTER_ROOT'] || File.expand_path(File.join('..', '..', 'flutter'))
if !File.exist?(flutter_root)
  flutter_root = File.expand_path(File.join('..', '..'))
end

require File.expand_path(File.join(flutter_root, 'packages', 'flutter_tools', 'bin', 'podhelper.rb'))

platform :ios, '13.0'

# 🌟 تأكيد استخدام الرؤوس النمطية بشكل عام
use_modular_headers!

target 'Runner' do
  use_frameworks!

  flutter_install_all_ios_pods File.dirname(File.expand_path(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    
    # تأكيد أخير على مستوى البودات المستقلة لـ Firebase
    target.build_configurations.each do |config|
      config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
      config.build_settings['DEFINES_MODULE'] = 'YES'
    end
  end
end
