# السطر القياسي والآمن لاستدعاء مساعد Flutter
target_local_podfile_path = File.expand_path(File.join('..', '..', 'flutter', 'packages', 'flutter_tools', 'bin', 'podhelper.rb'))
if File.exist?(target_local_podfile_path)
  require target_local_podfile_path
else
  # الحل المتوافق سحابياً لبيئات الـ GitHub Actions
  require_relative '../.flutter-plugins-dependencies' rescue nil
end

platform :ios, '13.0'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.expand_path(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    
    # 🌟 الحل الحاسم لإجبار Xcode على قبول ترويسات Firebase دون أخطاء معجمية
    target.build_configurations.each do |config|
      config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
    end
  end
end
