platform :ios, '13.0'

# تفعيل الأطر الديناميكية لحل مشكلة الفايربيس
use_frameworks!
use_modular_headers!

flutter_root = ENV['FLUTTER_ROOT'] || File.expand_path(File.join('..', '..', '..', '..', 'flutter'), __FILE__)
if !File.directory?(flutter_root)
  flutter_root = File.expand_path(File.join('..', '..', 'flutter'), __FILE__)
end

require File.join(flutter_root, 'packages', 'flutter_tools', 'bin', 'podhelper')

target 'Runner' do
  flutter_install_all_ios_pods File.dirname(__FILE__)
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    
    target.build_configurations.each do |config|
      # 1. توحيد إصدار النشر لمنع تعارض الفايربيس الحزم القديمة
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      
      # 2. إجبار المترجم على تجاهل التحذيرات القديمة وعدم تحويلها لأخطاء تفشل البناء
      config.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = 'NO'
      config.build_settings['SWIFT_TREAT_WARNINGS_AS_ERRORS'] = 'NO'
    end
  end
end
