name: Build All (Android & iOS)

on:
  push:
    branches: [ main ]

jobs:
  android-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.27.0'

      - name: Build Android APK
        run: |
          flutter pub get
          flutter build apk --debug --android-skip-build-dependency-validation

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-debug.apk

   ios-job:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.27.0'

      # 🌟 خطوة حاسمة: تعديل إعدادات Xcode الإجبارية للمشروع بالكامل لحل مشكلة Firebase Messaging
      - name: Inject Xcode Build Settings for Firebase
        run: |
          sed -i '' 's/CLANG_WARN_OBJC_ROOT_CLASS = YES;/CLANG_WARN_OBJC_ROOT_CLASS = YES;\n\t\t\t\tCLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES = YES;/g' ios/Runner.xcodeproj/project.pbxproj

      - name: Build iOS Application
        run: |
          flutter pub get
          flutter build ios --simulator --no-codesign --debug

      - name: Upload iOS App
        uses: actions/upload-artifact@v4
        with:
          name: ios-app-simulator
          path: build/ios/iphonesimulator/*.app
