name: iOS Build
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.22.2'

      - name: Force Generate iOS Dependencies
        run: |
          flutter clean
          flutter pub get
          cd ios
          # مسح ملفات الإعدادات القديمة لضمان إعادة توليدها
          rm -f .DS_Store
          rm -rf Pods
          rm -rf Flutter/ephemeral
          # إجبار فلاتر على تحديث مشروع الـ iOS
          cd ..
          flutter build ios --config-only

      - name: Build iOS App
        run: flutter build ios --release --no-codesign

      - name: Upload iOS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-app-bundle
          path: build/ios/iphoneos/*.app
