name: iOS Build
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.22.2'

      - name: Clean and Repair iOS
        run: |
          flutter clean
          flutter pub get
          # مسح مجلد الـ ios وإعادة إنشائه لضمان سلامة الملفات
          rm -rf ios/Flutter/ephemeral
          flutter precache --ios
          flutter build ios --config-only

      - name: Build iOS App
        run: flutter build ios --release --no-codesign

      - name: Upload iOS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-app-bundle
          path: build/ios/iphoneos/*.app
