name: iOS Build
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.22.2'

      - name: Update and Fix Dependencies
        run: |
          # تحديث التبعيات لتتوافق مع إصدار فلاتر في السيرفر
          flutter pub upgrade
          flutter pub get

      - name: Pre-build iOS
        run: |
          # توليد ملفات Xcode الضرورية
          flutter build ios --config-only --no-codesign

      - name: Build iOS App
        # استخدام الأمر المباشر لتجاوز فحص الحزم
        run: |
          flutter build ios --release --no-codesign

      - name: Upload iOS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-app-bundle
          path: build/ios/iphoneos/*.app
